### ISSUE TITLE
Stop here for l long time, can't enter game.How to build this project correctly?

### ISSUE THREAD

**Issue by kgho** [greggman/better-unity-webgl-template#16]
Unity: 2020.1.3f1c1

![Snipaste_2020-10-29_15-56-51](https://user-images.githubusercontent.com/21258030/97541073-81cd4380-19ff-11eb-9c97-e019b14c3e59.png)

**Comment by greggman** [comment]
You can't run Unity-WebGL directly from your hard-drive period. That has nothing to with this template. You'll get the same results with or without it.

To run Unity-WebGL you need a web server [Here's a simple one](https://greggman.github.io/servez)
