### ISSUE TITLE
The custom logo blocks the mobile warning dialog

### ISSUE THREAD

**Issue by simon-heinen** [greggman/better-unity-webgl-template#4]
![screenshot_20180928-225042_chrome](https://user-images.githubusercontent.com/3509660/46232888-08bb1800-c371-11e8-869f-3de2a9b91b15.jpg)

I would say the mobile warning dialog is not a good ux anyways and would remove it completely

**Comment by greggman** [comment]
think it's fixed.

Unfortunately there's no easy way to remove the dialog AFAIK. I didn't look too deeply but Unity is injecting the dialog rather than letting the template deal with it like it does for progress

**Comment by simon-heinen** [comment]
Yes works fine now, sad that unity enforces this error message.
